version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service
      MYSQL_USER: service_user
      MYSQL_PASSWORD: service_password
    restart: on-failure
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb